//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConversionHistory
    {
        public int Id { get; set; }
        public System.DateTime ConversionDate { get; set; }
        public double Amount { get; set; }
        public double ConvertedAmount { get; set; }
        public int FromCurrencyRateId { get; set; }
        public int ToCurrencyRateId { get; set; }
    
        public virtual CurrencyRate CurrencyRate { get; set; }
        public virtual CurrencyRate CurrencyRate1 { get; set; }
    }
}
